/**
 * Phase 2a — TypeScript mirror of the Python `OpeningKeySquare` schema.
 *
 * Mirrors `scripts/tabiya_build/schema.py::OpeningKeySquare` and
 * `scripts/tabiya_build/key_squares.py::KeySquareRecord` 1:1. The browser
 * loads these as part of `catalog.json` via `Opening.key_squares`.
 *
 * Constitution Article 14 — TS strict, no `any`. Article 5 — types live in
 * `src/types/`, repository surface in `src/storage/`.
 */

/** Role taxonomy — must match Python `KeySquareRole`. */
export type KeySquareRole = 'outpost' | 'control' | 'tension' | 'weak';

/** Side the square is meaningful FOR — must match Python `KeySquareColor`. */
export type KeySquareForColor = 'white' | 'black';

/**
 * One curated key square attached to an opening's canonical position.
 *
 * Distinct from `KeySquare` in `src/storage/types.ts` (the legacy free-text
 * annotation on `Line`). This is the role-typed, source-cited Phase 2a record
 * that the Phase 2b `<SpotlightOverlay>` renders.
 */
export type OpeningKeySquare = {
  /** Algebraic square notation, e.g. "d5", "f7". Must match /^[a-h][1-8]$/. */
  square: string;
  /** Role taxonomy entry. */
  role: KeySquareRole;
  /** Which side the square is meaningful for (used in tooltip). */
  for_color: KeySquareForColor;
  /** ≤280-char rationale. Surfaced as tooltip text on hover. */
  rationale: string;
  /** Permissive-licensed source URL. Audited at build time (Article 1). */
  source_url: string;
};

/**
 * Sidecar shape — `public/transpositions.json`, fetched lazily by
 * `src/storage/transpositions.ts`. Generated by
 * `scripts/tabiya_build/transposition.py::write_transposition_sidecar`.
 */
export type TranspositionSidecar = {
  /** Bumps when the hash algorithm or normalization rule changes. */
  schema_version: number;
  generated_at: string;
  /** Always "sha1-16" for schema_version=1. */
  fen_hash_algo: 'sha1-16';
  /** Always "drop-counters" for schema_version=1. */
  fen_normalization: 'drop-counters';
  /** Map fen_hash → sorted list of line IDs that share this position. */
  index: Record<string, string[]>;
};
